Feature/distributed move
ecmwf/fdb pull request #3
Opened 2023-03-21 22:13 UTC by danovaro

Initial implementation of the fdb-move distributed to many nodes.

the process with rank 0 is responsible for catalogue traversal, copy of indexes, and task dispatching to other processes.
Each task is a datafile to copy.

2023-03-21 22:14 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/fdb?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/fdb?pullRequest=3) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: b8raoult<br/>:x: oiffrig<br/>:x: danovaro<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/fdb?pullRequest=3) it.</sub>

2023-03-23 21:59 UTC, simondsmart requested changes
The sense of this is very clear. But the transfer of the FileCopy activity to the MPI workers needs tidying up. It is currently unsafe to long path names (could be fixed as simply as having ASSERTS that we don't hit that). But it would be better to use an eckit Buffer as the source/target, and use eckit::Store to get the data in/out.

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/tools/fdb-move-mpi.cc
> +            comm.template send<int>(&ready, 1, 0, 0);
Why is the template specifier needed here?

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/tools/fdb-move-mpi.cc
> +            MoveIterator list = fdb.move(request, destination_, !keep_, removeDelay_, mpi_, threads_);
This looks structurally like a non-MPI version of this could be created fairly straightforwardly from the same source file?

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/toc/TocStore.cc
> +                    it->second->str(task, 1024);
I assume that this 1024 here is sizeof(task). Please use that.

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/toc/TocCommon.h
> +        src_(srcPath / fileName), dest_(destPath / fileName) {}
Newline for dest_

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/toc/TocCommon.h
> +        bufr[l1] = '\0';
What happens here if l1 > size?

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/toc/TocCommon.h
> +        int l2 = dest_.asString().length();
This is going to be _very_ unhappy if we run out of buffer space.

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/tools/fdb-move-mpi.cc
> +        char task[1024];
why 1024? It is perfectly reasonable to have two paths that are longer than that in aggregate. Unlikely, perhaps, but by no means impossible.

Is this something that we should be constructing as, say 2*(PATH_MAX+1)?

2023-03-23 21:59 UTC, simondsmart commented on src/fdb5/toc/TocStore.cc
> +                    it->second->str(task, 1024);
This function ought to be something like encode().

If it were me, I would use the eckit::serialisation stuff to encode into a buffer.

2023-05-04 12:58 UTC, closed without merging