Feature list depth option
ecmwf/fdb pull request #34
Opened 2024-08-08 08:44 UTC by mcakircali

2024-08-13 11:10 UTC, simondsmart requested changes

2024-08-13 11:10 UTC, simondsmart commented on src/fdb5/tools/fdb-list.cc
> +        options_.push_back(new SimpleOption<bool>("porcelain",
Where supported, enforces and commits that output is maintained stably such that it can be used in scripts.

2024-08-13 11:10 UTC, simondsmart commented on tests/fdb/api/test_fdb_c.cc
> +            err = fdb_splitkey_metadata(sk, &k, &v, checkLevel ? &l : nullptr);
Revert this bit of the test.

2024-08-13 11:10 UTC, simondsmart commented on tests/fdb/api/test_fdb_c.cc
> +    const int depth = 3;
Can we have some tests with depth = 1, 2

2024-08-13 11:10 UTC, simondsmart commented on src/fdb5/api/local/ListVisitor.h
> +                queue_.emplace(KeyChain<2> {currentCatalogue_->key(), currentIndex_->key()}, eckit::URI {}, 0);
Once again, use the multiple constructors.

2024-08-13 16:30 UTC, mcakircali commented on src/fdb5/api/helpers/ListElement.cc
> +    ASSERT(loc_);
good point.. done!

2024-08-14 06:53 UTC, mcakircali commented on src/fdb5/api/FDB.cc
> +        return existing.attributes().timestamp < replacement.attributes().timestamp;
preserved

2024-08-14 07:00 UTC, mcakircali commented on src/fdb5/api/helpers/ListElement.h
> +    auto key() const -> const Key& { return key_; }
good point, preserved api. I cached on stack, plus notice return type constness

2024-08-14 07:17 UTC, mcakircali commented on src/fdb5/api/helpers/ListElement.h
> +    auto key() const -> const Key& { return key_; }
unfortunate point. the leading auto (trailing return type) was not introduced as a stylistic change in language. it has semantic purposes.

2024-08-14 13:55 UTC, mcakircali commented on src/fdb5/api/helpers/ListElement.cc
> +ListElement::ListElement(DatumKeys&& keys, const FieldLocation& location, const TimeStamp timestamp):
passing shared_ptr by value communicates intent better while causing multiple unneeded incr. in addition, uri_ { loc_->uri() } will crash if someone passes an empty location here

so, I chose const ref as it's safe and perf better here
FieldLocation::make_shared is flawed anyways, so it'll be a single place to fix later

2025-02-14 11:42 UTC, merged