Remote fdb
ecmwf/fdb pull request #54
Opened 2024-11-26 09:11 UTC by Ozaq

2024-11-26 14:48 UTC, Ozaq commented on src/fdb5/api/RemoteFDB.cc
> +};
This is unused

2024-11-26 14:48 UTC, Ozaq commented on src/fdb5/api/RemoteFDB.cc
>                          }
Formatting seems broken.

2024-11-27 10:44 UTC, tbkr requested changes
Quite a lot obsolete comment/commented-out code remarks.

There are some comments on changed logic as well, which may slipped through, while writing the code.

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/rules/MatchAny.h
> +	const eckit::ReanimatorBase& reanimator() const override { return reanimator_; }
Indenting

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/rules/Rule.cc
> +// void Rule::expandFirstLevel( const Key &dbKey, std::vector<Predicate *>::const_iterator cur, Key &result, bool& found) const {
Remove block

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/FileSpace.cc
> +        // AutoLock<Mutex> lock(mutex_);
Remove the autolock here

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/TocCatalogue.cc
> +// void TocCatalogue::visitEntries(EntryVisitor& visitor, /*const Store& store,*/ bool sorted) {
Remove block

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/TocCatalogue.h
> +    // void visitEntries(EntryVisitor& visitor, /*const Store& store,*/ bool sorted) override;
Remove

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/TocCatalogueWriter.cc
> +// selectIndex is called during schema traversal and in case of out-of-order fieldLocation archival
Remove

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/TocMoveVisitor.h
> +    // bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
Remove

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/TocPurgeVisitor.h
> +    // bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
Remove

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/TocStats.h
> +    // bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
Remove

2024-11-27 10:44 UTC, tbkr commented on src/fdb5/toc/TocWipeVisitor.cc
> +// bool TocWipeVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
Remove, also below

2024-11-27 13:05 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +                                throw eckit::SeriousBug(ss.str(), Here());
At the end of this code block it is considered to be a serious bug if the client id is unknown, however we only enter this code if there is ANY client ID. If there is no client ID the code will just continue with the next iteration of the for-ever loop. Is this intentional? I would argue that no client id is the same error case as an unknown client id.

2024-11-27 14:02 UTC, Ozaq commented on src/fdb5/remote/client/RemoteCatalogue.cc
> +    dataWrite(Message::Blob, id, payloads);
There is serialization and deserialization code in many places and I think this needs to be abstracted away into the read/write methods.

With the current implementation I see problems if we ever want to evolve the protocol, either by changing the serialization format or by introducing new / deprecating old fields.

I would like to see something along the lines of:

```cpp
struct MessageBlob {
  // Contains everything the message entails
};

auto msg = createMessage(...) // Or use a builder
write(msg) // This takes care of buffer handling & serialization
```

2024-11-28 22:55 UTC, danovaro commented on src/fdb5/api/FDB.h
> +    eckit::DataHandle* retrieve(const metkit::mars::MarsRequest& request, bool seekable = false);
DataHandle is an abstract type.
while retrieving from FDB, each DataHandle is a stream of data blobs (usually grib messages)
the seekable parameter is there to optionally request a seekable DataHandle (a DataHandle that is buffering in memory the current grib message, so the user can seek backwards, within the current message)

Clearly the API is not clear, but we do not impose any knowledge to the user.

2024-12-02 08:35 UTC, Ozaq commented on src/fdb5/api/FDB.h
> +    eckit::DataHandle* retrieve(const metkit::mars::MarsRequest& request, bool seekable = false);
Ok that makes sense, but as you mentioned this is not obvious from the API alone. Thanks for the clarification.

2024-12-09 13:20 UTC, danovaro commented on src/fdb5/api/FDB.h
> +    eckit::DataHandle* read(bool seekable, ListIterator& it, bool sorted = false);
sorted, thanks

2024-12-10 10:30 UTC, danovaro commented on src/fdb5/api/FDB.h
> +    eckit::DataHandle* read(bool seekable, ListIterator& it, bool sorted = false);
seekable data retrieval has been moved to another branch (feature/57-seekable)

2024-12-11 14:37 UTC, Ozaq commented on src/fdb5/api/local/ControlVisitor.cc
> +bool ControlVisitor::visitDatabase(const Catalogue& catalogue) { //, const Store& store) {
done

2024-12-11 14:37 UTC, Ozaq commented on src/fdb5/api/local/ControlVisitor.h
> +//    bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
done

2024-12-11 14:37 UTC, Ozaq commented on src/fdb5/api/local/DumpVisitor.h
> +//    bool visitDatabase(const Catalogue& catalogue, const Store& store) override {
done

2024-12-11 14:37 UTC, Ozaq commented on src/fdb5/toc/TocPurgeVisitor.h
> +    // bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
done

2024-12-11 14:38 UTC, Ozaq commented on src/fdb5/api/local/MoveVisitor.cc
> +//bool MoveVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 14:38 UTC, Ozaq commented on src/fdb5/api/local/PurgeVisitor.cc
> +//bool PurgeVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 14:38 UTC, Ozaq commented on src/fdb5/api/local/PurgeVisitor.h
> +//    bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
done

2024-12-11 14:38 UTC, Ozaq commented on src/fdb5/api/local/StatsVisitor.cc
> +// bool StatsVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 14:38 UTC, Ozaq commented on src/fdb5/api/local/WipeVisitor.cc
> +//bool WipeVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 14:43 UTC, Ozaq commented on src/fdb5/api/local/ListVisitor.h
> +//    bool visitDatabase(const Catalogue& catalogue, const Store& store) override {
done

2024-12-11 14:48 UTC, Ozaq commented on src/fdb5/api/RemoteFDB.h
> +//    using StoredMessage = std::pair<remote::Message, eckit::Buffer>;
done

2024-12-11 14:49 UTC, Ozaq commented on src/fdb5/daos/DaosCatalogue.cc
> +    // return DaosCatalogue::catalogueTypeName();
@danovaro This looks like a bug, the function does not return anything anymore.

2024-12-11 14:49 UTC, Ozaq commented on src/fdb5/database/Archiver.h
> +    // uint32_t id() const { return id_; }
done

2024-12-11 14:50 UTC, Ozaq commented on src/fdb5/database/BaseArchiveVisitor.cc
>      // eckit::Log::info() << "selectIndex " << idxKey << std::endl;
done

2024-12-11 14:55 UTC, Ozaq commented on src/fdb5/database/Catalogue.h
> +    // CatalogueReader(const Key& key, ControlIdentifiers controlIdentifiers, const fdb5::Config& config)
done

2024-12-11 14:56 UTC, Ozaq commented on src/fdb5/database/Catalogue.h
> +    // CatalogueWriter(const Key& key, ControlIdentifiers controlIdentifiers, const fdb5::Config& config)
done

2024-12-11 14:56 UTC, Ozaq commented on src/fdb5/database/Engine.h
> +// #include "fdb5/database/DB.h"
done

2024-12-11 14:56 UTC, Ozaq commented on src/fdb5/database/Engine.h
> +    // virtual std::vector<eckit::URI> allLocations(const Key& key, const Config& config) const = 0;
done

2024-12-11 14:57 UTC, Ozaq commented on src/fdb5/database/Engine.h
> +//    virtual std::vector<eckit::URI> writableLocations(const Key& key, const Config& config) const = 0;
done

2024-12-11 14:57 UTC, Ozaq commented on src/fdb5/database/Manager.cc
> +// eckit::URI Manager::location(const Key& key) {
done

2024-12-11 14:57 UTC, Ozaq commented on src/fdb5/database/Manager.cc
> +// std::vector<eckit::URI> Manager::writableLocations(const Key& key) {
done

2024-12-11 14:57 UTC, Ozaq commented on src/fdb5/database/Manager.h
> +    // eckit::URI location(const Key &key);
done

2024-12-11 14:57 UTC, Ozaq commented on src/fdb5/database/ReadVisitor.cc
> +
done

2024-12-11 14:57 UTC, Ozaq commented on src/fdb5/database/Store.cc
> +// std::unique_ptr<Store> StoreFactory::build(const eckit::URI& uri, const Config& config) {
done

2024-12-11 14:58 UTC, Ozaq commented on src/fdb5/database/Store.h
> +// TODO can we avoid using the schema here?
done

2024-12-11 14:58 UTC, Ozaq commented on src/fdb5/io/FieldHandle.h
> +    // std::string title() const override;
done

2024-12-11 14:58 UTC, Ozaq commented on src/fdb5/rados/RadosFieldLocation.cc
> +// RadosFieldLocation::RadosFieldLocation(const FileStore &store, const FieldRef &ref) :
done

2024-12-11 14:58 UTC, Ozaq commented on src/fdb5/rados/RadosFieldLocation.h
> +//#include "fdb5/toc/FieldRef.h"
done

2024-12-11 14:58 UTC, Ozaq commented on src/fdb5/rados/RadosStore.cc
> +// RadosStore::RadosStore(const eckit::URI& uri, const Config& config) :
done

2024-12-11 14:58 UTC, Ozaq commented on src/fdb5/remote/Connection.cc
> +// void Connection::write(remote::Message msg, bool control, const Handler& clientID, uint32_t requestID, const void* data, uint32_t length) {
done

2024-12-11 14:59 UTC, Ozaq commented on src/fdb5/remote/Connection.cc
> +// void Connection::writeControl(remote::Message msg, uint32_t clientID, uint32_t requestID, const void* data, uint32_t length) {
done

2024-12-11 14:59 UTC, Ozaq commented on src/fdb5/remote/Connection.h
> +//    bool exit_;
done

2024-12-11 14:59 UTC, Ozaq commented on src/fdb5/remote/Messages.h
> +// #include "fdb5/remote/Handler.h"
done

2024-12-11 14:59 UTC, Ozaq commented on src/fdb5/remote/Messages.h
> +    // MessageHeader(Message message, bool control, const Handler& clientID, uint32_t requestID, uint32_t payloadSize=0);
done

2024-12-11 14:59 UTC, Ozaq commented on src/fdb5/remote/client/Client.cc
> +// #include <random>
done

2024-12-11 14:59 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +    // ASSERT(it == clients_.end());
done

2024-12-11 15:00 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +        // ClientConnectionRouter::instance().deregister(*this);
done

2024-12-11 15:00 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +        // if (dataWriteFuture_.valid()) {
done

2024-12-11 15:00 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +    // std::lock_guard<std::mutex> lock(clientsMutex_);
done

2024-12-11 15:00 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +//    std::lock_guard<std::mutex> lock(requestMutex_);
I have removed the commented out code

2024-12-11 15:00 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +            // dataWriteFuture_ = std::async(std::launch::async, [this] { return dataWriteThreadLoop(); });
done

2024-12-11 15:01 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +// void ClientConnection::handleError(const MessageHeader& hdr, eckit::Buffer buffer) {
done

2024-12-11 15:01 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnection.cc
> +    // ClientConnectionRouter::instance().deregister(*this);
done

2024-12-11 15:01 UTC, Ozaq commented on src/fdb5/remote/client/ClientConnectionRouter.cc
> +    // std::lock_guard<std::mutex> lock(connectionMutex_);
done

2024-12-11 15:02 UTC, Ozaq commented on src/fdb5/remote/client/RemoteCatalogue.cc
> +void RemoteCatalogue::visitEntries(EntryVisitor& visitor, /*const Store& store,*/ bool sorted) {NOTIMP;}
done

2024-12-11 15:03 UTC, Ozaq commented on src/fdb5/remote/client/RemoteCatalogue.h
> +    // void handleException(std::exception_ptr e) override;
done

2024-12-11 15:03 UTC, Ozaq commented on src/fdb5/remote/client/RemoteStore.h
> +// class RemoteStoreArchiver;
done

2024-12-11 15:03 UTC, Ozaq commented on src/fdb5/remote/client/RemoteStore.h
> +    // void handleException(std::exception_ptr e) override;
done

2024-12-11 15:03 UTC, Ozaq commented on src/fdb5/remote/server/CatalogueHandler.cc
> +            // case Message::Flush: // notification that the client has sent all data locations for archival
done

2024-12-11 15:03 UTC, Ozaq commented on src/fdb5/remote/server/CatalogueHandler.cc
> +// Handled CatalogueHandler::handleData(Message message, uint32_t clientID, uint32_t requestID) {
done

2024-12-11 15:03 UTC, Ozaq commented on src/fdb5/remote/server/CatalogueHandler.cc
> +// Handled CatalogueHandler::handleData(Message message, uint32_t clientID, uint32_t requestID, /*eckit::net::Endpoint endpoint,*/ eckit::Buffer&& payload) {
done

2024-12-11 15:05 UTC, Ozaq commented on src/fdb5/remote/server/CatalogueHandler.cc
> +    // std::vector<std::pair<std::string, eckit::net::Endpoint>> stores;
done

2024-12-11 15:05 UTC, Ozaq commented on src/fdb5/remote/server/CatalogueHandler.cc
> +    // return *((catalogues_[id] = std::make_pair(single_ ? 1 : 2, CatalogueArchiver(dbKey, config_))).second.catalogue);
done

2024-12-11 15:05 UTC, Ozaq commented on src/fdb5/remote/server/CatalogueHandler.h
> +    // Handled handleData(Message message, uint32_t clientID, uint32_t requestID) override;
done

2024-12-11 15:07 UTC, Ozaq commented on src/fdb5/rules/MatchAlways.h
> +	const eckit::ReanimatorBase& reanimator() const override { return reanimator_; }
done

2024-12-11 15:07 UTC, Ozaq commented on src/fdb5/rules/MatchHidden.h
> +	const eckit::ReanimatorBase& reanimator() const override { return reanimator_; }
done

2024-12-11 15:08 UTC, Ozaq commented on src/fdb5/rules/MatchValue.h
> +	const eckit::ReanimatorBase& reanimator() const override { return reanimator_; }
done

2024-12-11 15:08 UTC, Ozaq commented on src/fdb5/rules/Matcher.h
> +//	const eckit::ReanimatorBase& reanimator() const override { return reanimator_; }
done

2024-12-11 15:08 UTC, Ozaq commented on src/fdb5/rules/Rule.cc
> +// void Rule::expandFirstLevel( const Key &dbKey, std::vector<Predicate *>::const_iterator cur, Key &result, bool& found) const {
done

2024-12-11 15:09 UTC, Ozaq commented on src/fdb5/rules/Rule.h
> +	const eckit::ReanimatorBase& reanimator() const override { return reanimator_; }
done

2024-12-11 15:09 UTC, Ozaq commented on src/fdb5/toc/AdoptVisitor.cc
>      // Log::info() << "selectDatum " << key << ", " << full << " " << length_ << std::endl;
done

2024-12-11 15:10 UTC, Ozaq commented on src/fdb5/toc/FileSpace.cc
> +    // LOG_DEBUG_LIB(LibFdb5) << eckit::BackTrace::dump() << std::endl;
done

2024-12-11 15:10 UTC, Ozaq commented on src/fdb5/toc/FileSpace.cc
>  //    std::vector<const Root&> visitables = visitable();
done

2024-12-11 15:10 UTC, Ozaq commented on src/fdb5/toc/TocCatalogue.cc
> +// void TocCatalogue::visitEntries(EntryVisitor& visitor, /*const Store& store,*/ bool sorted) {
done

2024-12-11 15:10 UTC, Ozaq commented on src/fdb5/toc/TocCatalogue.cc
> +    // if (schema_) {
done

2024-12-11 15:11 UTC, Ozaq commented on src/fdb5/toc/TocCatalogueWriter.cc
> +// selectIndex is called during schema traversal and in case of out-of-order fieldLocation archival
done

2024-12-11 15:11 UTC, Ozaq commented on src/fdb5/toc/TocCatalogue.h
> +    // void visitEntries(EntryVisitor& visitor, /*const Store& store,*/ bool sorted) override;
done

2024-12-11 15:12 UTC, Ozaq commented on src/fdb5/toc/TocHandler.h
> +    // TocHandler( const Key& key, const Config& config);
done

2024-12-11 15:12 UTC, Ozaq commented on src/fdb5/toc/TocMoveVisitor.cc
> +//bool TocMoveVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 15:12 UTC, Ozaq commented on src/fdb5/toc/TocPurgeVisitor.cc
> +//bool TocPurgeVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 15:12 UTC, Ozaq commented on src/fdb5/toc/TocPurgeVisitor.h
> +    // bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
done

2024-12-11 15:13 UTC, Ozaq commented on src/fdb5/toc/TocStats.cc
> +//bool TocStatsReportVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 15:13 UTC, Ozaq commented on src/fdb5/toc/TocStats.h
> +    // bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
done

2024-12-11 15:13 UTC, Ozaq commented on src/fdb5/toc/TocWipeVisitor.cc
> +// bool TocWipeVisitor::visitDatabase(const Catalogue& catalogue, const Store& store) {
done

2024-12-11 15:13 UTC, Ozaq commented on src/fdb5/toc/TocWipeVisitor.h
> +    // bool visitDatabase(const Catalogue& catalogue, const Store& store) override;
done

2024-12-11 15:19 UTC, Ozaq commented on src/fdb5/database/EntryVisitMechanism.h
> +    mutable Store* currentStore_ = nullptr;
done

2024-12-11 17:42 UTC, danovaro commented on src/fdb5/daos/DaosCatalogue.cc
> +    // return DaosCatalogue::catalogueTypeName();
fixed, thanks!

2024-12-18 08:17 UTC, danovaro commented on src/fdb5/database/Archiver.cc
> +            eckit::Log::info() << "Closing database " << *databases_[oldK].catalogue_ << std::endl;
thanks, done.

2025-01-14 09:09 UTC, merged